"""Init tables

Revision ID: bc70c566a457
Revises: 
Create Date: 2018-05-21 17:24:53.370328

"""
import sys
from os.path import abspath, dirname
sys.path.insert(0, dirname(dirname(dirname(dirname(abspath(__file__))))))

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc70c566a457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_code'), 'index', ['code'], unique=True)
    op.create_table('market',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_code'), 'market', ['code'], unique=True)
    op.create_table('index_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_date_unique', 'index_prices', ['date', 'index_id'], unique=True)
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_code'), 'stock', ['code'], unique=True)
    op.create_table('stock_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_date', sa.DateTime(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('expected_price', sa.Float(), nullable=False),
    sa.Column('max_52', sa.Float(), nullable=False),
    sa.Column('per', sa.Float(), nullable=False),
    sa.Column('growth_next_year', sa.Float(), nullable=False),
    sa.Column('growth_next_five_year', sa.Float(), nullable=False),
    sa.Column('dividend_yield', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('stock_date_unique', 'stock_data', ['date', 'stock_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stock_date_unique', table_name='stock_data')
    op.drop_table('stock_data')
    op.drop_index(op.f('ix_stock_code'), table_name='stock')
    op.drop_table('stock')
    op.drop_index('index_date_unique', table_name='index_prices')
    op.drop_table('index_prices')
    op.drop_index(op.f('ix_market_code'), table_name='market')
    op.drop_table('market')
    op.drop_index(op.f('ix_index_code'), table_name='index')
    op.drop_table('index')
    # ### end Alembic commands ###
